url: http://dev.abemedia.co.uk:4000
assets:
  compress:
    css: false
    js: false
pdf:
  debug: true

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
  -
    scope:
      path: ''
      type: cars
    values:
      layout: car
      pdf: true
  -
    scope:
      path: ''
      type: posts
    values:
      layout: blog_post