title: 'Karlsen Auto Design'
description: Karlsen
url: 'http://karlsen.abemedia.co.uk'
permalink: none
locale: en_GB
timezone: Europe/London
analytics:
  provider: google_analytics
sharing:
  provider:
    - facebook
    - twitter
    - google
    - linkedin
    - pinterest
    - stumbleupon
    - delicious
    - reddit
    - tumblr
    - buffer
  limit: 'false'
  style: icons
defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
  -
    scope:
      path: ''
      type: cars
    values:
      layout: car
      pdf: true
  -
    scope:
      path: ''
      type: posts
    values:
      layout: blog_post
collections:
  cars:
    output: true
    permalink: '/showroom/:path.html'
mediaurl: _media
assets:
  compress:
    css: false
    js: true
  digest: true
  sources:
    - bower_components
    - _assets/less
    - _assets/images
    - _assets/js
    - _media
baseurl: /
comments:
  provider: '1'
profiles:
  provider:
    - facebook
    - twitter
    - instagram
  facebook: 'https://www.facebook.com/kad911/'
  twitter: 'https://twitter.com/karlsenautodes'
  instagram: 'https://www.instagram.com/karlsenautodesign/'
exclude:
  - Gemfile*
  - bower*
  - README.md
  - vendor
bitly:
  username: karlsenautodesign
  api_key: R_3ea49b3df69e4af898f9662996e2b33c
pdf:
  debug: true
